# Flutter Rules
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.provider.** { *; }
-keep class io.flutter.game.** { *; }
-dontwarn io.flutter.embedding.handshake.**

# Keep native methods
-keepclasseswithmembernames class * {
    native <methods>;
}

# Hive Local Database Rules
-keep class com.notenest.ai.** { *; }
-keepclassmembers class * extends io.flutter.plugin.common.MethodChannel { *; }

# Google Fonts & Material Rules
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**

# AndroidX WorkManager, Room & Startup Rules (Fixes WorkDatabase R8 crash)
-keep class androidx.work.** { *; }
-keep class androidx.work.impl.** { *; }
-keep class androidx.work.impl.background.** { *; }
-keep class androidx.work.impl.WorkDatabase** { *; }
-keep class androidx.room.** { *; }
-keep class * extends androidx.room.RoomDatabase
-keep class * extends androidx.room.Entity
-keepclassmembers class * extends androidx.room.RoomDatabase {
    static ** *;
    <fields>;
    <methods>;
}
-keep class androidx.startup.** { *; }
-dontwarn androidx.work.**
-dontwarn androidx.room.**

# Google Mobile Ads Rules
-keep class com.google.android.gms.ads.** { *; }
-dontwarn com.google.android.gms.ads.**

# Flutter Play Core (Deferred Components / Split Install)
# These classes are part of Flutter embedding but NOT used in this app.
# Rules generated by Android Gradle plugin from missing_rules.txt
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
